# Efficiency Theory

So far we've learned how to pose a good causal question and we've examined what kinds of causal assumptions we might have to make in order to translate the causal estimand to an observable estimand. Now that we have an observable estimand, we're done with causality for the time being (until we return to interpreting our result in context of the causal assumptions). Now we are left with a purely statistical problem: we want to estimate some aspect of a distribution given some finite samples from that distribution.

The fact that identification and estimation can be cleanly separated is a wonderful feature of the modern approach to causal inference. The causal problem is that we don't observe the right "columns" (the potential outcomes) in the "population dataset". The statistical problem is that we don't observe all of the "rows".

\[footnote\] cite the uniform convergence thing in RCTs as a counterexample where ID and estimation interplay

In this chapter we will examine how to define whether an estimator is in some sense "optimal" for a given estimand. If you've already done some applied causal inference, you probably already know that there are many different practical approaches for estimating causal effects (matching, regression, inverse probability weighting, etc.). How can we judge these against each other when in reality we never observe the "truth" that all of them are trying to estimate? What reason might we have to choose one over another? Once we've developed a characterization of optimality, we will see in the next chapter how to use that knowledge to construct optimal estimators for many kinds of estimands.

As a heads up, this chapter is technical, so you will see a lot of pointers to the appendices, which explain foundational concepts in mathematical statistics. As a reminder, these are targeted at readers who have taken a course in basic probability and statistics, but perhaps not real analysis or measure-theoretic probability. The appendices by no means cover all of what there is to know about their respective topics. While I strive to be as rigorous as possible, the primary goal is not rigor but instead to give the reader a sense of why and how the concepts are most often used in asymptotic statistics so that they can begin to distinguish between the main ideas and the mathematical details in the literature.