::: content-hidden
{{< include _macros.qmd >}}
:::

# Asymptotic Linearity {#sec-3-AL}

## What do we want from estimators?

Let's forget about what we know about estimators for a second and start from scratch. What is it that we *want* from an estimator in the first place? Can we set some "deal-breaker" conditions or some "nice-to-haves"?

Recall that an estimator $\hat\Psi$ is a function that takes a dataset (which we represent as an empirical distribution) $\p_n$ and returns a number. We use $\hat\psi = \hat\Psi(\p_n)$ to denote the *estimate*, which is a random variable. In practice, however, the term "estimator" is often used to refer to both the function $\hat\Psi$ and the random variable $\hat\psi$ interchangeably.

Any estimator $\hat\Psi$ can be characterized by the distribution of $\hat\psi$ at each sample size $n$ from each distribution $\p \in \model$. What would we want these sampling distributions to look like relative to the true value $\psi = \Psi(\mathbb P)$?

Why not demand that the estimate is always *exactly* equal to the estimand, i.e. $\hat\Psi(\mathbb P_n) = \Psi(\mathbb P)$ for all distributions $\mathbb P$ in the model $\mathcal P$? That might seem completely absurd but it's worth taking a second to ask why that is really such a crazy thing to demand. It is less extreme to ask that our estimate is correct *on average*, but even this is usually not possible to do. So let's settle for asking that our estimator is *asymptotically* unbiased: the estimate is more or less right on average given a large-enough sample size. Informally: $\mathbb E[\hat\psi] \approx \psi$ for $n$ large enough.

If I have two estimators that are both unbiased, which is better? Since the total estimation error $\mathbb E[(\hat\psi - \psi)^2]$ can be decomposed to $\mathbb (E[\hat\psi]-\psi)^2 + \mathbb V[\hat\psi]$ (by adding and subtracting $\mathbb E[\hat\psi]$ inside the square and expanding), the unbiased estimator with the smallest overall error will be the one with the smallest variance. Therefore we should desire estimators that have small (asymptotic) sampling variance, subject to being (asymptotically) unbiased.

Let's throw in a practical consideration. When we estimate a quantity we usually report confidence intervals or p-values alongside the point estimate. Those inferential statistics depend on having some estimate of the sampling variance of our estimator, which we usually construct based on a theoretical understanding of what that sampling distribution should be. Many commonly used estimators are known to be asymptotically normal, which greatly facilitates inference. Therefore another desired criterion might be that our estimator should have a theoretically-understood sampling distribution.

Therefore a sensible list of desiderata for an estimator might be:

1.  asymptotically unbiased
2.  small asymptotic sampling variance
3.  well-understood sampling distribution

## Asymptotic Linearity

In light of these criteria, we will simplify the problem of finding an optimal estimator to finding an optimal estimator among those that are *asymptotically linear*. I'll lay out what that means, argue for why it's a reasonable restriction given our criteria above, and then explain why this restriction is helpful in characterizing optimality.

:::: callout-note
# Asymptotic Linearity

::: {#def-AL}
As before, assume that $Z_i$ are drawn IID from some distribution $\mathbb P$. An *asymptotically linear* estimator $\hat\psi$ is one that can be written like $$
\hat\psi = \psi + \frac{1}{n} \sum_i \phi(Z_i) + o_{\mathbb P}(n^{-1/2})
$$

for some mean-zero function $\phi$ with mean zero $\mathbb E[\phi(Z)]=0$ and finite variance $\mathbb V[\phi(Z)] < \infty$.
:::
::::

::: callout-warning
If you don't really understand what $o_{\mathbb P}(n^{-1/2})$ means in the definition above or why it implies the sample mean term "dominates" asymptotically, you should work through all of @sec-app-rv-convergence before returning here.
:::

The function $\phi$ is called the *influence function* of the estimator $\hat\psi$. A better name for it could be the "averaging transformation" of the data for a given estimator because once the data have been transformed by $\phi$, the estimator can be closely approximated by the truth plus a sample average of those transformed variables (which have mean zero). In large samples, sample averages of mean-zero variables behave like Gaussian random noise. It's somewhat remarkable that a huge number of very complicated estimators actually behave this way, as we will see shortly. By definition, every asymptotically linear estimator has an influence function that satisfies the above criteria: having one is what makes the estimator asymptotically linear.

::: {#exm-AL-sample-mean}
## Sample Mean

The sample mean estimator is one example of an asymptotically linear estimator. To see that, write $\hat\psi = \frac{1}{n} \sum Z_i$ as $$
\hat\psi - \psi = \frac{1}{n} \sum \underbrace{(Z_i - \psi)}_{\phi(Z_i)} + 0.
$$ For this estimator, the remainder term is exactly 0, which clearly satisfies the requirement of being $o_{\mathbb P}(n^{-1/2})$.
:::

The influence function for an estimator also depends on the distribution of the data. For example, in the case of the sample mean we saw that $\phi(z) = z - \psi$ which we should really write as $\phi_{\mathbb P}(z) = z - \Psi(\mathbb P)$ to emphasize that this particular influence function depends on the mean of $Z$ *under the distribution* $\mathbb P$. Often we write something like $\phi_{\mathbb P}(z)$ or even $\phi(\mathbb P)(z)$ to mean the influence function of a given estimator *at a particular distribution* $\mathbb P$. But more often than not we leave the $\mathbb P$ part implicit to minimize notational clutter.

In fact, it's more appropriate to say that an estimator is asymptotically linear *for some set of distributions*, i.e. within some model. But usually the restriction on the set of distributions is not particularly meaningful so we just say the estimator is "asymptotically linear (under regularity conditions)" and leave it at that.

:::: {.callout-important appearance="simple"}
::: {#exr-not-AL-sample-mean}
Let's presume that $Z$ are drawn from a distribution $\mathbb P$ such that $\sqrt n \left(\frac{1}{n}\sum Z_i\right)$ diverges as a random variable (see @sec-app-conv-bigO for a definition of divergence of random variables). A "textbook example" of such a distribution is $\text{Pareto}(1,1.5)$, but this happens for many "fat-tailed" distributions. You can ask your favorite large language model if you want to see a proof.

Why does this tell you that the sample mean cannot be asymptotically linear at $\mathbb P$?

The point of this example isn't to convince you that the sample mean isn't asymptotically linear (it is for essentially all distributions we care about), it's just to cement the idea that asymptotic linearity of an estimator technically depends on what distributions you're talking about and to better understand the definition by considering a counterexample.
:::
::::

It's totally possible for two different estimators to have the same influence function (at each distribution). This is because two different algorithms can turn out to behave very similarly as the sample size increases. For example, we could construct a very silly alternative estimator for the mean by adding $1/n$ to our sample mean estimate. This extra term is certainly converging to zero at better than a $\sqrt{n}$ rate so it is negligible and the influence function for our alternative estimator is the same as for the sample mean. We'll also see the idea of two different estimators sharing an influence function come up later when we discuss different strategies for building optimal estimators: the estimators we get from using each strategy may be different, but they all have the same influence function and therefore all behave similarly in large-enough samples.

At this point you may be worried about how you can take your favorite estimator and derive its influence function. It's often possible to prove an estimator is aymptotically linear, but in this book we actually won't need to do that. We're going to go the other direction: starting from the estimand, we're going to come up with a way to determine the "best" possible influence function and then *construct* an estimator around it.

## Benefits of AL Estimators {#sec-AL-benefits}

Given our desiderata, asymptotically linear (AL) estimators are a very sensible class of estimators to restrict ourselves to. For one, AL estimators are guaranteed to be consistent: that is, they converge to the estimand in probability and are thus asymptotically unbiased. This is guaranteed by the fact that any influence function $\phi$ is mean-zero so the associated sample mean converges to 0 by the law of large numbers.

:::: {.callout-important appearance="minimal"}
::: {#exr-AL-zero-estimator}
Consider the silly estimator $\hat\psi = 0$ when attempting to estimate the population mean $\mathbb E[Z]$ in a model containing all possible finite-mean distributions of $Z$. Is this estimator asymptotically linear across the entire model? Why or why not?
:::
::::

Another related benefit of asymptotically linear estimators is that they satisfy our practical requirement of understanding the sampling distribution. By the central limit theorem, $\psi + \mathbb P_n \phi$ looks more and more like $\psi + \norm(0, \mathbb V[\phi(Z)]/n)$ as the sample size increases. The remaining term $o_{\mathbb P}(n^{-1/2})$ is negligible in comparison (by definition). More often you will see this written formally as $$\sqrt{n} (\hat\psi - \psi) \rightsquigarrow \norm(0, \sigma_*^2)
$$ where $\sigma_*^2 = \mathbb V[\phi(Z)] = \mathbb P \phi^2$ (since $\phi$ has mean zero).

We call $\sigma^2_*$ the *asymptotic variance* of our estimator. You should think of $\hat\psi - \psi$ as a normal distribution that is shrinking towards a spike at $0$: its variance is decreasing at a rate of $n^{-1/2}$ by the central limit theorem (see @exm-stochastic-bounding-clt in @sec-app-conv-bigO). We therefore "stabilize" the shrinking distribution of $\hat\psi - \psi$ by "blowing it up" by a factor of $\sqrt n$. The asymptotic variance $\sigma^2_*$ is the variance of this stable normal distribution (compare rows 1 and 3 of the figure in @fig-littleo-densities). It is *not* the limit of the sampling variance $\mathbb V[\hat\psi]$ as a function of $n$ because that limit is always zero on account of the fact that the estimate is converging to the estimand.

At any finite sample, the standard error of the estimate is roughly given by $\sigma = \frac{\sigma_*}{\sqrt n}$. Since the asymptotic variance is given by the variance of the influence function, understanding the influence function is all we need to understand the sampling distribution.

Constructing asymptotically valid confidence intervals and p-values for any asymptotically linear estimator is therefore as simple as estimating $\sigma^2_* = \mathbb P \phi^2$. If we can construct an estimate $\hat\sigma_*$ that is close to $\sigma_*$ for large-enough $n$ then we can estimate the standard error of our estimate with $\hat\sigma = \frac{\sigma_*}{\sqrt n}$ we will get asymptotic 95% coverage of $\psi$ with an interval of the form $[\hat\psi - 2\hat\sigma/\sqrt{n}, \hat\psi + 2\hat\sigma/\sqrt{n}]$ (this is a "Wald-type" confidence interval).

:::: {.callout-important appearance="minimal"}
::: {#exr-wald-interval}
# Wald Interval

a.  Assuming that $\sqrt{n} (\hat\psi - \psi) \sim \norm(0, \sigma^2)$, prove that $\hat{\mathbf C} = [\hat\psi \pm 2\sigma/\sqrt{n}]$ is a 95% confidence interval, i.e. $\mathbb P \{\psi \in \hat{\mathbf C}\} > 0.95$.
b.  Assuming asymptotic linearity, how does our actual knowledge of the sampling distribution of $\hat\psi$ compare to what we assumed in part (a)?
c.  In the real world our confidence interval is $[\hat\psi \pm 2\hat\sigma/\sqrt{n}]$. How does this compare to what we used in part (a)?
d.  Given (b) and (c), do you think the real-world confidence interval will generally have better-than 95% coverage for all sample sizes?

:::
::::

::: {#exm-sample-mean-var-IF}
## Variance of the sample mean

In the case of the sample mean estimator $\hat\psi = \frac{1}{n} \sum Z_i$ we previously saw the influence function was $\phi(z) = z - \psi$. A plug-in estiamate of $\mathbb P\phi^2$ is therefore given by $\frac{1}{n} \sum \hat\phi(Z_i)^2 = \frac{1}{n} \sum (Z_i - \hat\phi)^2$
:::

::: {#exm-ols-var-IF}
## Variance of ordinary least squares coefficients

Let's say we're trying to estimate the regression coefficients in a linear model. Let $(Y,X) \sim \mathbb P$ with $X \in \mathbb R^d$. Let $\beta_0 = \text{argmin}_\beta \mathbb E\left[(Y - X\beta)^2\right]$ be the coefficients that minimize the population mean squared error. This will be our estimand. We haven't assumed the $Y$ vs. $X$ relationship is truly linear, we're just estimating the best linear approximation. As an estimator we will use the ordinary least squares (OLS) estimate $\hat\beta = \text{argmin}_\beta \frac{1}{n} \sum \left[(Y_i - X_i\beta)^2\right]$.

It is a well-known result that the OLS estimator is asymptotically linear under mild regularity conditions. For one proof of this see chapter 5 of Asymptotic Statistics (but it's not important at the moment). The influence function is $$
\phi(x,y) = \mathbb E[XX^\top]^{-1} x(y - x^\top \beta)
$$

You may recognize this because it's where the "sandwich" estimator (also known as "Huber-White" or "robust" estimator) of the standard error comes from. The (asymptotic) sandwich standard error is a plug-in estimate for the quantity $\mathbb E[XX^\top]^{-1} \mathbb E[X(Y - X^\top \beta)^2 X^T] \mathbb E[XX^\top]^{-1}$, which is nothing other than $\mathbb P \phi\phi^\top$, i.e. the equivalent of $\mathbb P \phi^2$ when $\phi$ is a vector-valued function (as is the case when the estimand is a vector).

In this example the dependence on $\mathbb P$ is through the expectation $\mathbb E[XX^\top] = \mathbb E_{\mathbb P}[XX^\top]$ and the true best regression coefficients $\beta = \beta_{\mathbb P}$. As usual, I've left off the explicit dependence on $\mathbb P$ in the notation.

The interesting thing about this example is that computing the estimate involves a fairly complex algorithm: either gradient descent or a series of matrix multiplications and inversions. It's not a "simple" estimator like the sample mean. Nonetheless, in large enough samples, the estimator behaves as if if were just a sample mean of a transformation of the data.

OLS is a special case of a huge class of estimators called M-estimators. Others include sample quantiles, robust regressions, and many others. All of these are asymptotically linear under mild regularity conditions.
:::

In our list of desired characteristics we also wrote that we wanted estimators to have as small a variance as possible. Asymptotic linearity by itself doesn't guarantee small variance, but it does give us a very easy way to compare two estimators. If we have estimators $\hat\psi_1$ and $\hat\psi_2$ which are both asymptotically linear, then all we need to know to decide which one is better (in large-enough samples) is to compare their asymptotic variances which are given by $\mathbb P \phi_1^2$ and $\mathbb P \phi_2^2$.

You may also recognize $\mathbb P \phi^2$ as the squared $\mathcal L_2(\mathbb P)$ norm of $\phi$. Therefore we are comparing $\|\phi_1\|$ to $\|\phi_2\|$. In other words, the better estimator is whichever has the "smaller" influence function! In the following sections this is the key insight we will use to construct optimal estimators.

::: callout-warning
If you are unfamiliar with $\mathcal L_2$ spaces or don't understand why $\mathbb P \phi^2$ is a norm, you should work through through @sec-app-L2-vectors and @sec-app-L2-L2 now.
:::

The theory of optimality we are building is only valid for asymptotically linear estimators. If there were many practically useful estimators that were *not* AL, this could be a problem because we would not able to usefully compare them. We'll discuss this more in a later section but the short answer is that AL estimators are an extremely broad class and we're not leaving much of anything on the table.