filters:
  - diagram
  - mathbb-to-mathds
  - exm-end

diagram:
  cache: true
  engine:
    tikz:
      header-includes:
        - '\usepackage{tikz, tikz-3dplot, amsmath, amsfonts, amssymb, pgfplots, accents, adjustbox, dsfont, array, booktabs}'
        - '\usetikzlibrary{arrows, angles, quotes, arrows.meta, shapes, calc, backgrounds}'

project:
  type: book
  output-dir: docs

from: markdown+emoji

book:
  title: "Foundations of Modern Causal Inference"
  author: "Alejandro Schuler, Mark van der Laan"
  chapters:
    - index.qmd
    - part: 1-0-intro.qmd
      chapters:
      - 1-1-estimation-problems.qmd
      - 1-2-causality.qmd
      - 1-3-scm.qmd
    - part: 3-0-intro.qmd
      chapters:
      - 3-2-regularity.qmd
      - 3-3-efficiency.qmd
      - 3-4-deriving-eifs.qmd
      - 4-1-plugin-expansion.qmd
    - 6-references.qmd
  appendices:
    - 5-1-rv-convergence.qmd
    - 5-2-L2.qmd
    # - 5-3-derivatives.qmd

execute:
  freeze: auto  # re-render only when source changes
  # eval: false

callout-icon: false

bibliography: references.bib

# must generate html and pdf SEPARATELY for tikz to work!!
format:
  html:
    css: styles.css
    code-fold: true
    warning: false
    theme:
      - cosmo
      - brand
    grid:
      body-width: 1200px
  pdf:
    echo: false
    latex-output-dir: pdf
    # keep-tex: true
    include-in-header:
      - text: |
          \usepackage{dsfont}

# finish counterfactual causality history
# some soft exercises in counterfactual causality ch
# add history sections to efficiency theory chapters
# explain \dot f notation (at earliest use) as any linear function tangent to f shifted to orign (directional derivative; recall it w/ subsequent uses)
# fix all the intro chapters / sections
# add correlation vs causation pic from what it
