filters:
  - diagram

diagram:
  cache: true
  engine:
    tikz:
      header-includes:
        - '\usepackage{tikz, tikz-3dplot, amsmath, amsfonts, pgfplots, accents, adjustbox}'
        - '\usetikzlibrary{arrows, angles, quotes, arrows.meta, shapes, calc}'

project:
  type: book
  output-dir: docs

from: markdown+emoji

book:
  title: "Introduction to Modern Causal Inference"
  author: "Alejandro Schuler, Mark van der Laan"
  chapters:
    - index.qmd
    - part: 3-0-intro.qmd
      chapters:
      - 3-1-AL.qmd
      - 3-2-regularity.qmd
      - 3-3-efficiency.qmd
    - part: 4-0-intro.qmd
      chapters:
      - 4-1-plugin-expansion.qmd
    - 6-references.qmd
  appendices:
    - 5-1-rv-convergence.qmd
    - 5-2-L2.qmd

execute:
  freeze: auto  # re-render only when source changes
  # eval: false

callout-icon: false

bibliography: references.bib

# must generate html and pdf SEPARATELY for tikz to work!!
format:
  html:
    code-fold: true
    warning: false
    theme:
      - cosmo
      - brand
    grid:
      body-width: 1200px
  pdf:
    keep-tex: true
    echo: false
