# Introduction {.unnumbered}

Our goal is to get people with any amount of experience in formal mathematics past undergraduate probability to be able to take a vaguely-defined scientific question, translate it into a formal statistical problem, and solve it by constructing a tool that is optimal for the job at hand.

This book is about fundamentals, not applications. If you're eager to do applied data analysis and write code, another book like @mixtape-causal-inf or @causalML will probably get you there faster. However, if you're interested in understanding how to formulate new causal questions from scratch, how frameworks like double machine learning and targeted learning actually work, or what all the inscrutible symbols in mathematical causal inference papers mean, then you've come to the right place. You will learn all that and much more from this book, and I think that you will find the investment well worth your time even if your ultimate aim is to do applied work. You will be a much stronger researcher and a more discerning critic once you are fluent in the language of modern causal inference.

## Topics

This book aims to be a relatively self-contained treatment of the modern approach to causal inference. 

The book is divided into two parts, which mirrors the division between the "causal" and "inference" parts of causal inference. Roughly speaking, the first part of the book is about how to ask meaningful questions, whereas the latter is about how to answer them effectively. This is a distinguishing factor vis-a-vis other popular texts on causal inference which lump the two together on a setting-by-setting basis, e.g., @causalML, @mixtape-causal-inf. Both have advantages: I believe that the former structure is more useful to learn the foundations (which is the purpose of this book) whereas the latter is more useful to dive into applications.

Part I starts with statistical models, often described with directed acyclic graphs, and estimands, which formalize the notions of what we already know and what we would like to discover from a data analysis (i.e., what we would calculate deterministically if we had infinite data, money, etc.). We then proceed to formalize *causal* models, which expand the kinds of questions we can ask, and identification, which helps us understand what we need to assume to answer these questions with the kind of data we have in the real world. We cover potential outcomes and nonparametric structural equations models as two essentially interchangeable lenses or perspectives with which to view causality. The material on causality and identification condenses what can be found in more expansive texts like @causality-pearl, using examples similar to those in, e.g., @mixtape-causal-inf, but focused on the identification rather than estimation.

In Part II we describe estimation, which is how to turn observed data into an answer for our question. Because the data we collect are "random" (usually dependent on some sampling process), we rarely get a deterministic answer and so we need to understand what makes an answer-guessing algorithm (estimator) good or bad. To do that we take a tour through efficiency theory, which is mathematically demanding, but gives us the superpower of characterizing mathematically optimal estimators with something called the *efficient influence function*. The material on efficiency theory in this book is most similar in scope and scale to the first few chapters of both @tsiatis and @bkrw. Lastly, we describe methods to operationalize that superpower by constructing optimal estimators in the double machine learning and targeted learning frameworks. Here the book is similar to @causalML or @targeted-learning, but with more of a focus on foundations rather than examples and applications.

As you can see from the outline above, while the material overlaps with many other resources, this book is unique in covering the foundations of both causality and efficient inference in one place. Among books covering efficiency theory, it is also unique in not assuming a background in analysis and probability theory.

## Philosophy and Pedagogy

This book is rooted in the philosophy of modern causal inference. What sets this philosophy apart are the three following tenets:

1.  The first is that for most practical purposes, **the point of statistics *is* causal inference**. Ultimately, we humans are concerned with how to make decisions under uncertainty that lead to the best outcome. These are fundamentally causal questions that ask "*what if*" we did A instead of B? The machinery of statistical inference is agnostic to causality, but that doesn't change the fact that our motivation in using it isn't. Therefore there is little point in shying away from causal claims because non-causal claims are not often of any practical utility.
2.  That leads to the second, often misunderstood point, which is that **there is no such thing as a method for causal inference**. This isn't a failing of the statistics literature so much as a failing of the naive popularization of new ideas (e.g. blog posts, low-quality papers). The process of statistical inference (for point estimation) only cares about estimating a parameter of a probability distribution and quantifying the sampling distribution of that estimate. There is nothing "causal" about that, and many are surprised to learn that the algorithms used for "causal" inference are actually identical to those used to make non-causal statements. What makes an analysis causal has little if anything to do with the estimator or algorithm used. It has everything to do with whether or not the researcher can satisfy certain non-testable assumptions about the process that generated the observed data. It's important to keep these things (statistical inference and causal identification) separated in your mind even though they must always work together.
3.  The last and perhaps greatest shortcoming of traditional statistics pedagogy is that it generally does not teach you to ask the question that makes sense scientifically and *then* translate it into a statistical formalism. This is partly because, in the past, our analytic tools were quite limited and no progress could be made unless one imposed unrealistic assumptions or changed the question to fit the existing methods. Today, however, **we have powerful tools that can then translate a given statistical problem into an optimal method for estimation** in a wide variety of settings. It's not always totally automatic, but at a minimum it provides a clear way to think about what's better and what's worse. It liberates you from the route if-this-kind-of-data-then-that-method thinking that only makes for bad statistics and bad science.

Taken together, these three points give this movement a clear, unified, and increasingly popular perspective on causal inference. We have no doubt whatsoever that this is the paradigm that will come to dominate common practice in the next decades and century.

We’ve chosen an approach for this particular text that focuses on the following principles:

1.  **Foundations with fewer prerequisites**. Many students are turned off or intimidated by the amount of mathematical formality that is required to rigorously understand modern causal inference. While you don’t actually need a lot of math to use and understand the ideas, you do need *some* math to be able to work independently in the field. Since one of our goals is for you to be able to *construct your own* efficient estimator for a never-before-seen problem, we have to think precisely and not hand-wave away rigor.

    For better or worse, the math you need is built on several layers of prerequisites- real analysis, probability theory, functional analysis, and asymptotic statistics (more on that later). In an ideal world, we would all have taken these courses and be prepared for what’s next, but in practice we know many people have gaps in their knowledge.

    In this book we try to address that by providing a lot of foundational background information about these topics, either in the main text or weaved in as pointers to the appendices. We do our best to build up intuition for the component pieces of things before diving into implications. We lean heavily on figures and natural English prose to explain these concepts alongside the formal mathematical notation. We emphasize intuition and practical alongside formalism. At a minimum, we try to be very clear about what the foundations actually *are* so that if you don’t understand something you at least know where to look.

2.  **Core concepts**. Modern causal inference is a huge field. There are so many exciting applications and theoretical developments that it can be hard for students to find their way at first.

    We've tried to keep thing as short and concise as possible in this book by focusing on core ideas and a limited number of examples. The point of this is to emphasize what is most important and to allow you to learn the fundamentals without getting distracted. That means there are many topics that aren't covered in this book (see section below), but the idea is that this book will give you the tools and mindset you need in order to continue your learning productively.

3.  **A welcoming voice.** Modern causal inference is fast-moving and intense. It’s easy to feel like you don’t belong or aren’t good enough to participate. The agnostic, impersonal tone that is best for writing a clear academic paper doesn’t always create the warm, emotional connection that is necessary for us to feel secure and ready to learn.

    To deal with that problem, the voice we use throughout this book is informal and relatively nonacademic. I write in the first person and address you, the reader, directly. We provide personal commentary alongside agnostic technical material. All of this is deliberate and meant to help you feel comfortable and guided through this world. You are not alone in learning!

### Foundations with Fewer Prerequisites

Despite my best efforts, you will need *some* background material to get the most out of this book. The "hard" prerequisites listed are non-negotiable (this book will make no sense to you at all if you don't know what a probability distribution is), but the "soft" prerequisites are completely optional.

I often get asked why modern causal inference is so hard, or why it can't be summarized in a good way for general audiences to be able to understand it. It's a fair question to ask, but it's sort of like asking why a layperson isn't able to build a rocket and go to the moon, or why an amateur cyclist can't win the Tour de France. If you want to do hard things, you have to put up with some level of complexity and go through all of the layers of prerequisites to get where you want to go.

Just be patient with yourself, you will get there. And, like every other skill, once you have enough practice with the fundamentals, it really will seem easy (even though it's not!). Surely you find reading easy, but that's because you don't remember the years of work you put into it as a child, sounding out every single letter and learning to recognize words.

**Hard Prerequisites** You'll need to know probability theory at the undergraduate level. Random variables, expectation, conditional expectation, probability densities, etc. should be familiar to you, and perhaps you have a vague understanding of what convergence in distribution means. You should also be familiar with linear regression. Chapters 1-6, 9, and 13 of *All of Statistics* [@all-of-stats] or Chapters 1-5 of *Foundations of Angnostic Statistics* [@agnostic-statistics] are great places to review these topics.

It may go without saying, but you also need undergraduate multivariable calculus and linear algebra: integrals, derivatives, vectors, etc. should all be well-worn tools at your disposal. If you're shaky on these topics, I recommend [Khan Academy](https://www.khanacademy.org/). I also encourage you to check out the real analysis and measure-theoretic probability resources listed below, which will provide you with a very useful conceptual understanding.

**Soft Prerequisites** Real analysis, measure-theoretic probability, and asymptotic statistics aren't necessary to grasp the arc of the arguments I'll make, but a fully rigorous understanding isn't possible without them. I try to provide a self-contained and accessible introduction to the required topics in the appendices, but if you find yourself looking for more, the books and videos given below constitute what I think is the most self-contained treatment of their respective topics that is in line with the didactic approach taken in this book. My recommended texts tend to have a more conversational tone, provide more background and intuition to the reader, and have plenty of worked examples. As always, however, there are many alternatives that may work better for you depending on your needs. These subjects should be tackled in the order they are listed here:

| Field | Topics to Focus On | Resources |
|------------------------|------------------------|------------------------|
| 1\. Intro Real Analysis | sequences, limits, series, continuity, convergence (pointwise, uniform), derivative | [Real Analysis YouTube Lectures](https://www.youtube.com/playlist?list=PLBh2i93oe2quABbNq4I_-hyjhW8eOdgrO), [*Understanding Analysis* (Ch 1-6)](https://www.math.ucdavis.edu/~babson/MAT127B/abbott-second-edition.pdf) @analysis |
| 2\. Measure-Theoretic Probability | definition and construction of measure, Lebesgue integral and its properties, Radon-Nikodym theorem, change-of-variables formula, modes of convergence for random variables, independence, central limit theorem, conditional expectation | [*Measure Theory Youtube Lectures*](https://www.youtube.com/playlist?list=PLo4jXE-LdDTQq8ZyA8F8reSQHej3F6RFX), [*Measure, Integral, and Probability*](https://s2pnd-matematika.fkip.unpatti.ac.id/wp-content/uploads/2019/03/Marek-Capinski-Peter-E.-Kopp-Measure-integral-and-probability-Springer-2004.pdf) @probability |
| 3\. Functional Analysis in $\mathcal L_2$ | projection, bounded dual space, Reisz representation | [*Introductory Functional Analysis with Applications* (Ch 1-3)](https://physics.bme.hu/sites/physics.bme.hu/files/users/BMETE15AF53_kov/Kreyszig%20-%20Introductory%20Functional%20Analysis%20with%20Applications%20(1).pdf) @functional-analysis |
| 4\. Asymptotic Statistics | convergence of random variables, testing and estimation, properties of estimators | [*Asymptotic Statistics*](https://www.cambridge.org/core/books/asymptotic-statistics/A3C7DAD3F7E66A1FA60E9C8FE132EE1D) @vdv |

### Core Concepts

We've done our best to keep this book lean and targeted on foundational concepts. As a consequence, there are many important and interesting topics that we’ll say nothing or little about. For the sake of completeness, we'll list some of them here so you know where to start looking when you're ready to build on your solid foundation.

To keep things simple and consistent, most of the examples in this book focus on inference of the average treatment effect in simple covariate-treatment-outcome observational or randomized studies. However, there are many data structures which are much more elaborate than this. For example, we do not fully discuss inference in longitudinal settings with time-varying covariates and treatments, inference when some outcomes are censored, stochastic interventions, or continuous treatments. Non-IID data (e.g. treatment spillover in a network) is another interesting topic that is not covered. We also do not discuss randomization inference or Bayesian estimators. Nonetheless, what is in this book will prepare you to study all of these topics and to understand them as special cases or extensions of the general approach presented here.

While the tools we describe in this book are extremely powerful, they are not *all*-powerful. Some estimands of legitimate interest are not "pathwise differentiable" and therefore cannot be analyzed with these tools. An important example of such an estimand is the conditional average treatment effect, which is the subject of extensive research. There is not yet a unified approach to these problems.

Another interesting and useful setting that we do not discuss is online (or reinforcement) learning. Many topics related to this literature (e.g. off-policy evaluation) are directly addressable with the methods in this book, but here we omit all discussion of scenarios where the treatment policy can be manipulated during data collection as more information comes in. The framework for causal inference we develop in this book does extend to such settings but only with some added complexity that is best understood after learning the basics.

### Other Books

If this book doesn't fit your needs, I recommend the following texts. I pull from many of these in this book, whereas others are good references or follow-ons. The descriptions are my subjective opinions.

| Text | Description |
|------------------------------------|------------------------------------|
| Causality, @causality-pearl | An excellent book on the rigorous foundations of causal models with much more detail than is given in this book. Does not require much math. No discussion of estimation. |
| Asymptotic Statistics, @vdv | A rigorous and thorough coverage of theoretical asymptotic statistics, overlapping this book in its coverage of efficiency theory. A great book to work through after doing analysis and measure-theoretic probability if you are interested in theory. Demands maturity but doesn't shy away from providing informal insights as well. |
| Efficient and Adaptive Estimation for Semiparametric Models, @bkrw | A rigorous treatment of efficiency theory, covering more ground than this book in that area. Relatively dense and requires background in measure theory and analysis, but not entirely unforgiving. No discussion of causality or more modern estimators like double machine learning and targeted learning. |
| Semiparametric Theory and Missing Data, @tsiatis | A detailed look at semi-parametric theory with many examples in causal inference and censored data problems. Less focus on the theoretical fundamentals than this book, and a bit more traditional in perspective. |
| Causal Inference: The Mixtape, @mixtape-causal-inf | Very accessible and friendly treatment of popular causal inference settings such as regression discontinuity and difference-in-differences. More detail on those settings than provided here, but grounded in intuition rather than mathematical formalism. Mostly traditional approaches to estimation. |
| Causal Inference: What If?, @what-if | Shines in describing the kinds of problems that arise in real-world data. Not heavily technical, which is a strength, but doesn't provide the fundamentals of efficiency theory. |
| Applied Causal Inference Powered by ML and AI, @causalML | Applied tour of how to use machine learning tools in common causal inference settings. Not much foundational background, but an extremely useful reference for how to actually do these analyses. Recommend after this book. |
| Targeted Learning in Data Science, @targeted-learning | Many examples (including code!) of constructing targeted learning estimators for different problems as well as variations on targeted learning. I recommend tackling it after this book because their description of the fundamentals is relatively brief. |

## How to Read This Book

You may be surprised to find reading instructions for a book beyond "read left-to-right, top-to-bottom, turn page when done", but actually most of us are very bad at reading technical books (mathematicians and statisticians included).

Since we're so used to reading casual prose, or, worse yet, scrolling through posts, reading math can be very, very difficult. In math, you can't skim and get the gist of things: you need to actually read everything and think carefully about it. In fact, reading and thinking about it isn't enough, either - you need to do some problems and struggle a little for things to sink in. Over time, you'll also find yourself revisiting and relearning things, finding deeper insights and connections each time.

Why do you need to read and think slowly? For one, the ideas expressed are usually unfamiliar abstractions. We're pretty good at reasoning about concrete situations we've been in before, but when a new idea is introduced that seems very unattached from everyday experience, it takes dedicated attention for it to sink in. A second reason is that mathematics is often expressed in notation, one of whose purposes it is to make it faster to write complicated ideas down. But the cost of making it easier to write is that it can be harder to read for novices. An equation can contain as much information in one line as an entire paragraph or page of prose can contain. You wouldn't expect yourself to read a page in one second and understand it, so you shouldn't expect the same from an equation either.

When you encounter an equation you should **slow down**. Before thinking about what it says, make sure you understand what kind of object each of the symbols is. If you're a programmer familiar with typed or object oriented languages, this is like identifying the class or formal type of each object in the expression. Knowing who all the "characters" are in the story usually helps to understand the "plot", i.e., the meaning of the equation. I've tried to write this book to help you do that automatically. I usually say things like "the influence function $\phi$" instead of just "$\phi$", and after important theorems or equations I walk through each part and the implications. But it should also be a habit that you try to build for yourself. Lastly, once you understand the "story" of an equation or theorem, you try understand its "themes": how does the result connect to other concepts?

Another way I've tried to help you in this book is by providing exercises throughout the text. The exercises function a little like speed bumps in the road: they're there to remind you to slow down. I've tried to make most of them fairly easy in the sense that they are basic concept checks or re-applying a theme from a previously worked example, but there are also some that are a bit more challenging so you shouldn't feel bad if you get stuck. Getting stuck is part of the process, but my rule of thumb is that if you spend more than 30 minutes on a problem without substantial progress or insight or learning, then you should consult a friend or advisor or temporarily move on. Nonetheless, my intent is that you **attempt all the exercises as you read**. Please do not skip over them: you will very quickly lose the thread of the book and waste your time. 

I've also scattered a few warning boxes throughout the text to point out places where you might need some background material. I expect people reading this book will have very different levels of experience with asymptotic statistics and analysis so I have written fairly extensive appendices that can be worked through as needed. The warning boxes in the text specify which appendices are necessary to understand what parts of the book: these will mainly be invoked in the efficiency theory and estimation chapters. If you aren't familiar with the concepts, going to the appendix and working through the corresponding sections is non-negotiable. If you try to skip over things, you will not learn anything and again waste your time.

In terms of clock time, you should probably budget on the order of several hours per chapter. Your mileage may vary but I hope it helps to set a realistic expectation.

Again, I want to remind you that learning math from a book is a struggle for everyone, mathematicians and statisticians included. Most of us hate how slow reading is and really just wish that a friendly genius would come and explain everything to us in plain language. This book is trying to do that for you, but it's a book and not a person so you have to let it guide you and not rush.

## Issues, Edits, and Discussion

This book is entirely written in [Quarto](https://quarto.org/) and hosted on [GitHub](https://github.com/alejandroschuler/mci).

I welcome any questions and proposals for changes. Are you an instructor and you'd like to add a particular exercise or section to the book? Make an issue! Did you work through an example and find a typo? Fork the repository and make a pull request! Have a general question about something where the text isn't clear? Open a discussion. I hope that the discussion page in particular can be a place for lively discussion between learners and faculty who are using this book. You are welcome and even encouraged to ask me questions directly there.

| Page | URL | Purpose |
|------------------------|------------------------|------------------------|
| [Issues](https://github.com/alejandroschuler/mci/issues) | [github.com/alejandroschuler/mci/issues](github.com/alejandroschuler/mci/issues) | Point out errors or propose larger changes to the text. |
| [Pulls](https://github.com/alejandroschuler/mci/pulls) | [github.com/alejandroschuler/mci/pulls](github.com/alejandroschuler/mci/pulls) | Propose concrete changes. Typos or rephrasings can go straight to a pull request. No need to open an issue, but make sure each PR stays small. |
| [Discussions](https://github.com/alejandroschuler/mci/discussions) | [github.com/alejandroschuler/mci/discussions](github.com/alejandroschuler/mci/discussions) | Ask content questions and contribute to discussion about the material. |

## Acknowledgements

The authors thank Kaitlyn Lee, Shira Mitchell, Lauren Liao, and Kat Hoffman for productive comments on chapter drafts.